namespace TextTool.Interop;

public enum EverythingStatus
{
    OK,
    ERROR_MEMORY,
    ERROR_IPC,
    ERROR_REGISTERCLASSEX,
    ERROR_CREATEWINDOW,
    ERROR_CREATETHREAD,
    ERROR_INVALIDINDEX,
    ERROR_INVALIDCALL,
}
