//<auto-generated/>

#pragma warning disable
#nullable enable

namespace TextTool.SourceGenerators.Attributes
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public class PropertyComparisonProviderAttribute : global::System.Attribute
    {
        public const string Name = "PropertyComparisonProvider";
    }
}
